# Generated by Django 3.2.4 on 2021-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_balance',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
