# Generated by Django 3.2.4 on 2021-06-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_balance_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('from_date_time', models.DateTimeField()),
                ('to_date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
