# Generated by Django 3.2.4 on 2021-06-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_request_status_vacations_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vacations',
            options={'ordering': ['from_date_time']},
        ),
        migrations.AlterField(
            model_name='vacations',
            name='status',
            field=models.IntegerField(),
        ),
    ]
