# Generated by Django 3.2.4 on 2021-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210608_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacations',
            name='to_date_time',
            field=models.DateTimeField(),
        ),
    ]
