# Generated by Django 3.2.4 on 2021-06-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_vacations_to_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_balance',
        ),
        migrations.AlterModelOptions(
            name='vacations',
            options={'ordering': ['from_date_time']},
        ),
    ]
