# Generated by Django 3.2.4 on 2021-06-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210611_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacations',
            name='status',
        ),
    ]
