# Generated by Django 3.2.4 on 2021-06-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_vacations_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacations',
            options={},
        ),
    ]
