# Generated by Django 3.2.4 on 2021-06-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_vacations_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leave_type',
        ),
    ]
